import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { defineConfig } from "wxt";

const RULES_DIR = join(import.meta.dirname, "public", "generated", "rules");

/**
 * Static DNR rulesets generated by packages/filter-engine/scripts/build-rules.ts (`bun run rules`
 * runs before every dev/build). Each list is split into chunks like easylist-1.json.
 */
function ruleResources() {
  if (!existsSync(RULES_DIR)) return [];
  return readdirSync(RULES_DIR)
    .filter((file) => file.endsWith(".json"))
    .sort((a, b) => a.localeCompare(b, "en", { numeric: true }))
    .map((file) => ({
      id: file.replace(/\.json$/, ""),
      enabled: true,
      path: `generated/rules/${file}`,
    }));
}

// See https://wxt.dev/api/config.html
export default defineConfig({
  manifestVersion: 3,
  manifest: {
    name: "Semantic Blocker",
    description: "Blocks ads and sponsored content, including native ads that filter lists miss.",
    // Keep this list minimal. Adding a permission requires an ADR (see docs/adr/0005).
    permissions: ["storage", "declarativeNetRequest", "scripting"],
    host_permissions: ["<all_urls>"],
    declarative_net_request: { rule_resources: ruleResources() },
    browser_specific_settings: {
      gecko: {
        id: "{34b90a60-332d-4b5f-a9cc-3117035fe7cb}",
        // Remote semantic classification sends sanitized page-structure summaries, so it is opt-in.
        data_collection_permissions: { required: ["none"], optional: ["websiteContent"] },
      },
    },
  },
});
